export const polyLendAbi = [
    {
        type: "function",
        name: "loans",
        inputs: [{ name: "", type: "uint256" }],
        outputs: [
            { name: "borrower", type: "address" },
            { name: "lender", type: "address" },
            { name: "positionId", type: "uint256" },
            { name: "collateralAmount", type: "uint256" },
            { name: "loanAmount", type: "uint256" },
            { name: "rate", type: "uint256" },
            { name: "startTime", type: "uint256" },
            { name: "minimumDuration", type: "uint256" },
            { name: "callTime", type: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "requests",
        inputs: [{ name: "", type: "uint256" }],
        outputs: [
            { name: "borrower", type: "address" },
            { name: "positionId", type: "uint256" },
            { name: "collateralAmount", type: "uint256" },
            { name: "minimumDuration", type: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "offers",
        inputs: [{ name: "", type: "uint256" }],
        outputs: [
            { name: "requestId", type: "uint256" },
            { name: "lender", type: "address" },
            { name: "loanAmount", type: "uint256" },
            { name: "rate", type: "uint256" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "nextLoanId",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "nextRequestId",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "nextOfferId",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getAmountOwed",
        inputs: [
            { name: "_loanId", type: "uint256" },
            { name: "_paybackTime", type: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "conditionalTokens",
        inputs: [],
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "usdc",
        inputs: [],
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "AUCTION_DURATION",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "MAX_INTEREST",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "PAYBACK_BUFFER",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },

    {
        type: "function",
        name: "request",
        inputs: [
            { name: "_positionId", type: "uint256" },
            { name: "_collateralAmount", type: "uint256" },
            { name: "_minimumDuration", type: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "offer",
        inputs: [
            { name: "_requestId", type: "uint256" },
            { name: "_loanAmount", type: "uint256" },
            { name: "_rate", type: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "accept",
        inputs: [{ name: "_offerId", type: "uint256" }],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "repay",
        inputs: [
            { name: "_loanId", type: "uint256" },
            { name: "_paybackTimestamp", type: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "call",
        inputs: [{ name: "_loanId", type: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "transfer",
        inputs: [
            { name: "_loanId", type: "uint256" },
            { name: "_newRate", type: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "reclaim",
        inputs: [{ name: "_loanId", type: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "cancelRequest",
        inputs: [{ name: "_requestId", type: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "cancelOffer",
        inputs: [{ name: "_id", type: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },

    // Events
    {
        type: "event",
        name: "LoanRequested",
        inputs: [
            { name: "id", type: "uint256", indexed: false },
            { name: "borrower", type: "address", indexed: false },
            { name: "positionId", type: "uint256", indexed: false },
            { name: "collateralAmount", type: "uint256", indexed: false },
            { name: "minimumDuration", type: "uint256", indexed: false },
        ],
    },
    {
        type: "event",
        name: "LoanOffered",
        inputs: [
            { name: "id", type: "uint256", indexed: false },
            { name: "lender", type: "address", indexed: false },
            { name: "loanAmount", type: "uint256", indexed: false },
            { name: "rate", type: "uint256", indexed: false },
        ],
    },
    {
        type: "event",
        name: "LoanAccepted",
        inputs: [
            { name: "id", type: "uint256", indexed: false },
            { name: "startTime", type: "uint256", indexed: false },
        ],
    },
    {
        type: "event",
        name: "LoanCalled",
        inputs: [
            { name: "id", type: "uint256", indexed: false },
            { name: "callTime", type: "uint256", indexed: false },
        ],
    },
    {
        type: "event",
        name: "LoanTransferred",
        inputs: [
            { name: "oldId", type: "uint256", indexed: false },
            { name: "newId", type: "uint256", indexed: false },
            { name: "newLender", type: "address", indexed: false },
            { name: "newRate", type: "uint256", indexed: false },
        ],
    },
    {
        type: "event",
        name: "LoanRepaid",
        inputs: [{ name: "id", type: "uint256", indexed: false }],
    },
    {
        type: "event",
        name: "LoanReclaimed",
        inputs: [{ name: "id", type: "uint256", indexed: false }],
    },

    // Errors
    { type: "error", name: "OnlyBorrower", inputs: [] },
    { type: "error", name: "OnlyLender", inputs: [] },
    { type: "error", name: "InvalidLoan", inputs: [] },
    { type: "error", name: "InvalidOffer", inputs: [] },
    { type: "error", name: "InvalidRequest", inputs: [] },
    { type: "error", name: "InvalidRate", inputs: [] },
    { type: "error", name: "InvalidRepayTimestamp", inputs: [] },
    { type: "error", name: "CollateralAmountIsZero", inputs: [] },
    { type: "error", name: "CollateralIsNotApproved", inputs: [] },
    { type: "error", name: "InsufficientAllowance", inputs: [] },
    { type: "error", name: "InsufficientCollateralBalance", inputs: [] },
    { type: "error", name: "InsufficientFunds", inputs: [] },
    { type: "error", name: "LoanIsCalled", inputs: [] },
    { type: "error", name: "LoanIsNotCalled", inputs: [] },
    { type: "error", name: "MinimumDurationHasNotPassed", inputs: [] },
    { type: "error", name: "AuctionHasEnded", inputs: [] },
    { type: "error", name: "AuctionHasNotEnded", inputs: [] },
] as const;

// Minimal ERC20 ABI (Solady USDC with mint)
export const usdcAbi = [
    {
        type: "function",
        name: "balanceOf",
        inputs: [{ name: "owner", type: "address" }],
        outputs: [{ name: "result", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "allowance",
        inputs: [
            { name: "owner", type: "address" },
            { name: "spender", type: "address" },
        ],
        outputs: [{ name: "result", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "approve",
        inputs: [
            { name: "spender", type: "address" },
            { name: "amount", type: "uint256" },
        ],
        outputs: [{ name: "", type: "bool" }],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "mint",
        inputs: [
            { name: "_to", type: "address" },
            { name: "_amount", type: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "decimals",
        inputs: [],
        outputs: [{ name: "", type: "uint8" }],
        stateMutability: "pure",
    },
] as const;

// Minimal ConditionalTokens ABI (ERC1155 + Gnosis CT functions)
export const conditionalTokensAbi = [
    {
        type: "function",
        name: "balanceOf",
        inputs: [
            { name: "owner", type: "address" },
            { name: "id", type: "uint256" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isApprovedForAll",
        inputs: [
            { name: "owner", type: "address" },
            { name: "operator", type: "address" },
        ],
        outputs: [{ name: "", type: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setApprovalForAll",
        inputs: [
            { name: "operator", type: "address" },
            { name: "approved", type: "bool" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "safeTransferFrom",
        inputs: [
            { name: "from", type: "address" },
            { name: "to", type: "address" },
            { name: "id", type: "uint256" },
            { name: "value", type: "uint256" },
            { name: "data", type: "bytes" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "splitPosition",
        inputs: [
            { name: "collateralToken", type: "address" },
            { name: "parentCollectionId", type: "bytes32" },
            { name: "conditionId", type: "bytes32" },
            { name: "partition", type: "uint256[]" },
            { name: "amount", type: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "mergePositions",
        inputs: [
            { name: "collateralToken", type: "address" },
            { name: "parentCollectionId", type: "bytes32" },
            { name: "conditionId", type: "bytes32" },
            { name: "partition", type: "uint256[]" },
            { name: "amount", type: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "prepareCondition",
        inputs: [
            { name: "oracle", type: "address" },
            { name: "questionId", type: "bytes32" },
            { name: "outcomeSlotCount", type: "uint256" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getConditionId",
        inputs: [
            { name: "oracle", type: "address" },
            { name: "questionId", type: "bytes32" },
            { name: "outcomeSlotCount", type: "uint256" },
        ],
        outputs: [{ name: "", type: "bytes32" }],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "getCollectionId",
        inputs: [
            { name: "parentCollectionId", type: "bytes32" },
            { name: "conditionId", type: "bytes32" },
            { name: "indexSet", type: "uint256" },
        ],
        outputs: [{ name: "", type: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getPositionId",
        inputs: [
            { name: "collateralToken", type: "address" },
            { name: "collectionId", type: "bytes32" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "pure",
    },
] as const;
